### PR TITLE
fix(frontend): Agent Tools & Metadata not available for V1 conversations 

### LINKED ISSUE #12169: "Agent Tools & Metadata" not available for V1 conversations
## Description

The "Show Agent Tools & Metadata" option in the context menu is not available for V1 conversations. This feature only works for V0 conversations because the code explicitly filters for V0 events when looking for the system message.

### Current Behaviour

- **In V0 conversations**: The "Show Agent Tools & Metadata" option appears in the Tools context menu and conversation name context menu
- **In V1 conversations**: The option is hidden because no system message is found

Image

## Expected Behaviour

> [!NOTE]
> The PR implementing this change should include sufficient test coverage. A test-driven development approach is preferred.

The "Show Agent Tools & Metadata" option should be available for both V0 and V1 conversations, displaying the appropriate system prompt and tools information based on the conversation version.

## Relevant Files

- [`use-conversation-name-context-menu.ts`](https://github.com/OpenHands/OpenHands/blob/main/frontend/src/hooks/use-conversation-name-context-menu.ts)
- [`type-guards.ts`](https://github.com/OpenHands/OpenHands/blob/main/frontend/src/types/v1/type-guards.ts)

### PR DESCRIPTION
**Pull request by kub938**
## Summary of PR
- Fixed an issue where the Agent Tools & Metadata list and modal were not displayed in V1.
- Updated systemMessage handling to accommodate both V0 and V1 message types.
- Defined the SystemMessageForModal interface and added ChatCompletionToolParam[] type for tools.
- In V1, the appropriate data for openhands_version and agent_class was not found, so they are currently set to null. I would appreciate guidance on how to improve this.

## Change Type
- [v] Bug fix

## Checklist
- [v] I have read and reviewed the code and I understand what the code is doing.
- [v] I have tested the code to the best of my ability and ensured it works as expected.

## Fixes
Resolves #12169 

## Release Notes
- [ ] Include this change in the Release Notes.

### CODE REVIEW

**Review by hieptl — COMMENTED** [review]
Hello @kub938, thank you for submitting this pull request. Could you please add tests to cover your changes? Thank you! 🙏

**Comment by kub938** [comment]
Sure! I'll add some tests to cover these changes and update the PR soon. Thanks for the guidance!

**Comment by kub938** [comment]
# Changes Made

## 1. SystemMessage UI Rendering & Interaction Tests
- Verify Button Rendering: Confirmed that the "Show Agent Tools" button is correctly rendered within the ToolsContextMenu.
- Data Display Validation: Verified that the adapted data is accurately displayed in the SystemMessageModal.
- Integration Flow: Confirmed that clicking the "Show Agent Tools" button successfully triggers the modal and displays the expected adapted content.

## 2. adaptSystemMessage Logic Tests
- Content Mapping: Verified that the function correctly transforms input data and outputs the intended content.
- Edge Case Handling: Confirmed that the function returns null as expected when an empty array ([]) is provided as input.

## 3. Extracted adaptSystemMessage logic
- Extracted adaptSystemMessage logic into src/utils/system-message-adapter.ts. This separates business logic from UI concerns and allows for independent unit testing.

File: frontend/src/utils/system-message-adapter.ts [hunk 1]
```diff
@@ -0,0 +1,48 @@
...
+  tools: ChatCompletionToolParam[] | Record<string, unknown>[] | null;
+  openhands_version: string | null;
+  agent_class: string | null;
+}
+
+export function adaptSystemMessage(
+  events: OHEvent[],
+): SystemMessageForModal | null {
+  let systemMessage: SystemMessageForModal | null = null;
+  // 여기의 events타입은 2가지가 들어올 수 있다. v0와 v1타입
```
Comment (amanape) [inline frontend/src/utils/system-message-adapter.ts]: Please translate comments to English, thank you!

File: frontend/__tests__/components/context-menu/tools-context-menu.test.tsx [hunk 2]
```diff
@@ -0,0 +1,71 @@
+import { describe, it, expect, vi } from "vitest";
+import { render, screen } from "@testing-library/react";
+import React from "react";
+import { adaptSystemMessage } from "#/utils/system-message-adapter";
+import { EventState } from "#/stores/use-event-store";
+import { SystemMessageModal } from "#/components/features/conversation-panel/system-message-modal";
+import { ToolsContextMenu } from "#/components/features/controls/tools-context-menu";
+
+// 기존의 로직이 v0 를 기준으로 짜여져 있고 v1 타입에 대한 어댑팅을 추가한 것이기 때문에 v1 타입에 대한 테스트를 추가
+// 이 로직이 정상적으로 작동되면 system message 모달에서 v1 타입의 system prompt가 정상적으로 표시됨
```
Comment (amanape) [inline frontend/__tests__/components/context-menu/tools-context-menu.test.tsx]: Please translate comments to English, thank you!

**Review by amanape — CHANGES_REQUESTED** [review]
Thank you, I’ve simplified and separated your test files. I just have a few requests:

File: frontend/__tests__/components/context-menu/tools-context-menu.test.tsx (hunk 2 above)
Comment (kub938) [reply frontend/__tests__/components/context-menu/tools-context-menu.test.tsx]: Sorry about that! I’ve deleted them since they were redundant.

File: frontend/src/utils/system-message-adapter.ts (hunk 1 above)
Comment (kub938) [reply frontend/src/utils/system-message-adapter.ts]: Sorry about that! I’ve deleted them since they were redundant.

**Comment by kub938** [comment]
Thank you for merging the PR!
