### PR TITLE
Fix: branch/repo dropdown reset on click

### LINKED ISSUE #12419: [Bug]: branch dropdown toggles on press, even when editing the branch via typing
### Is there an existing issue for the same bug? (If one exists, thumbs up or comment on the issue instead).

- [x] I have checked the existing issues.

### Describe the bug and reproduction steps

when trying to edit the name of the branch I'm looking for the dropdown toggles and resets what i was typing to the selected branch

### steps to reproduce

1. click the branch form field and see the dropdown options appear
2. start typing to search for a specific branch
3. click branch form field to edit your search 
4. see the dropdown fold back 

Image

### OpenHands Version

1.1.0

### Operating System

MacOS 26.2

### PR DESCRIPTION
**Pull request by abhayymishraa**
## Summary of PR

This PR fixes cursor position jumping and input resetting issues in the branch and repository dropdown components.

### Changes:
1. **Cursor position fix**: Uses direct `onChange` handler instead of downshift's `onInputValueChange` to preserve cursor position when editing in the middle of input text (addresses [downshift issue #217](https://github.com/downshift-js/downshift/issues/217))

2. **Dropdown stability fix**: Added `stateReducer` to both dropdowns to prevent dropdown from closing when clicking on the input field while it's open

3. **Input sync fix**: Simplified `useEffect` logic to only sync input value with selected item when dropdown is closed, preventing text reset while user is typing

## Demo Screenshots/Videos

https://github.com/user-attachments/assets/06ede378-76b8-4c9e-9718-4fd97c312e3f

## Change Type

- [x] Bug fix
- [ ] New feature
- [ ] Breaking change
- [ ] Refactor
- [ ] Other (dependency update, docs, typo fixes, etc.)

## Checklist

- [x] I have read and reviewed the code and I understand what the code is doing.
- [x] I have tested the code to the best of my ability and ensured it works as expected.

## Fixes

Resolves #12419 

## Release Notes

- [x] Include this change in the Release Notes.

Fixed cursor jumping to end of input when editing branch or repository names in dropdown search fields.

### CODE REVIEW

**Comment by hieptl** [comment]
Hello @abhayymishraa,

Thank you for your work on this pull request. Could you please add tests to cover the changes you’ve introduced? This will help ensure the behavior is well validated and prevent potential regressions in the future.

Please let us know if you need any support or clarification while adding the tests.

Thank you very much! 🙏

**Comment by abhayymishraa** [comment]
Sure @hieptl

**Comment by abhayymishraa** [comment]
Hi @hieptl , tests are failing because of the main branch test cases are failing

**Comment by hieptl** [comment]
Hello @abhayymishraa, I will review this pull request tomorrow. Thank you very much! 🙏

**Comment by abhayymishraa** [comment]
Thank You @hieptl

**Comment by abhayymishraa** [comment]
Hi @hieptl  any update

File: frontend/src/components/features/home/git-repo-dropdown/git-repo-dropdown.tsx [hunk 1]
```diff
@@ -220,8 +212,12 @@ export function GitRepoDropdown({
     onSelectedItemChange: ({ selectedItem: newSelectedItem }) => {
       handleSelectionChange(newSelectedItem);
     },
-    onInputValueChange: handleInputValueChange,
     inputValue,
+    stateReducer: (state, actionAndChanges) =>
```
Comment (hieptl) [inline frontend/src/components/features/home/git-repo-dropdown/git-repo-dropdown.tsx:218]: **suggestion:** Could you please consider adding an inline comment to explain the purpose of the stateReducer? This would help future developers better understand why it is needed. Thank you! 🙏

File: frontend/__tests__/components/features/home/git-branch-dropdown.test.tsx
Comment (hieptl) [inline frontend/__tests__/components/features/home/git-branch-dropdown.test.tsx:1]: **suggestion:** While you are adding tests for git-branch-dropdown.tsx, could you please also consider adding tests for git-repo-dropdown.tsx to ensure your changes to that component are fully covered as well? Thank you! 🙏

Comment (abhayymishraa) [reply frontend/__tests__/components/features/home/git-branch-dropdown.test.tsx:1]: sure, i'll go ahead and add it

File: frontend/src/components/features/home/git-repo-dropdown/git-repo-dropdown.tsx (hunk 1 above)
Comment (abhayymishraa) [reply frontend/src/components/features/home/git-repo-dropdown/git-repo-dropdown.tsx:218]: sure, will add it

File: frontend/__tests__/components/features/home/git-repo-dropdown.test.tsx [hunk 2]
```diff
@@ -0,0 +1,237 @@
...
+import { describe, expect, vi, beforeEach, it } from "vitest";
+import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
+import userEvent from "@testing-library/user-event";
+import { GitRepoDropdown } from "../../../../src/components/features/home/git-repo-dropdown/git-repo-dropdown";
+import { GitRepository } from "#/types/git";
+
+// Mock the repository data hook
+const mockUseRepositoryData = vi.fn();
+vi.mock(
+  "../../../../src/components/features/home/git-repo-dropdown/use-repository-data",
```
Comment (hieptl) [inline frontend/__tests__/components/features/home/git-repo-dropdown.test.tsx]: **question:** Would it be possible to use a pattern like this? Thank you! 🙏 

```ts
vi.mock("#/components/.../use-repository-data", ...)
```

Comment (abhayymishraa) [reply frontend/__tests__/components/features/home/git-repo-dropdown.test.tsx]: sorry sorry, tab completion did that, will fix it

**Comment by abhayymishraa** [comment]
@hieptl updated according to you!

**Comment by hieptl** [comment]
Thank you! 🙏
