### PR TITLE
fix(frontend): some user interface elements are overlapping with the Create API Key modal

### LINKED ISSUE #11291: [Bug]: Some user interface elements are overlapping with the Create API Key modal
### Is there an existing issue for the same bug? (If one exists, thumbs up or comment on the issue instead).

- [x] I have checked the existing issues.

### Describe the bug and reproduction steps

Image

Reproduction Steps:
1. Access the application in SaaS mode, navigate to the Settings page, and open the API Keys section.
2. Click the Create API Key button.
3. Observe the modal that appears.

### OpenHands Installation

Docker command in README

### OpenHands Version

_No response_

### Model Name

_No response_

### Operating System

None

### Logs, Errors, Screenshots, and Additional Context

N/A.

### PR DESCRIPTION
**Pull request by hieptl**
- [ ] This change is worth documenting at https://docs.all-hands.dev/
- [ ] Include this change in the Release Notes. If checked, you **must** provide an **end-user friendly** description for your change below

**End-user friendly description of the problem this fixes or functionality this introduces.**

Image

Reproduction Steps:
1. Access the application in SaaS mode, navigate to the Settings page, and open the API Keys section.
2. Click the Create API Key button.
3. Observe the modal that appears.

---
**Summarize what the PR does, explaining any non-trivial design decisions.**

The PR fixes some user interface elements are overlapping with the Create API Key modal.

We can refer to the image below for the output of the PR.

api-keys-modal-solution

---
**Link of any specific issues this addresses:**

Resolves #11291

---

To run this PR locally, use the following command:

GUI with Docker:
```
docker run -it --rm   -p 3000:3000   -v /var/run/docker.sock:/var/run/docker.sock   --add-host host.docker.internal:host-gateway   -e SANDBOX_RUNTIME_CONTAINER_IMAGE=docker.all-hands.dev/all-hands-ai/runtime:360b786-nikolaik   --name openhands-app-360b786   docker.all-hands.dev/all-hands-ai/openhands:360b786
```

CLI with uvx:
```
uvx --python 3.12 --from git+https://github.com/All-Hands-AI/OpenHands@hieptl/all-3903#subdirectory=openhands-cli openhands
```

### CODE REVIEW

File: frontend/src/components/shared/modals/modal-backdrop.tsx [hunk 1]
```diff
@@ -20,7 +20,7 @@ export function ModalBackdrop({ children, onClose }: ModalBackdropProps) {
   };
 
   return (
-    <div className="fixed inset-0 flex items-center justify-center z-20">
+    <div className="fixed inset-0 flex items-center justify-center z-[9999]">
```
Comment (amanape) [inline frontend/src/components/shared/modals/modal-backdrop.tsx]: It is usually best practice to avoid setting the maximum z index and try increasing the current z index instead (e.g., z-30, z-40, etc)

Comment (hieptl) [reply frontend/src/components/shared/modals/modal-backdrop.tsx]: Hi @amanape, I've updated the code based on your feedback. Thank you for your feedback! 🙏
