### PR TITLE
fix(frontend): performance and loading state bugs

### LINKED ISSUE #12704: [Bug]: Resizing browser window triggers slow reload in long V1 conversations
### Is there an existing issue for the same bug?

- [x] I have checked the existing issues.

### Describe the bug and reproduction steps

When using the OpenHands UI with a long V1 conversation, resizing the browser window across the mobile/desktop breakpoint (1024px) triggers a reload that can take **30 seconds to over a minute** to complete. During this time, the conversation displays a skeleton loader.

**Reproduction Steps:**

1. Start a V1 conversation and interact with it until there are many messages (the longer the conversation, the more noticeable the issue)
2. Wait at least 30 seconds after the last interaction
3. Resize the browser window to cross the 1024px width threshold (e.g., from 1200px to 900px, or vice versa)
4. Observe that a skeleton loader appears and the conversation takes a very long time to reload

**Expected Behavior:**

Resizing the window should be instantaneous or near-instantaneous. The conversation history is already loaded and should not need to be refetched.

**Actual Behavior:**

The UI shows a loading skeleton for 30+ seconds while it appears to refetch and reprocess the entire conversation history.

### OpenHands Version

1.2.x (V1 conversations)

### Operating System

All (observed on macOS, but likely affects all platforms)

### Additional Context

- The issue is proportional to conversation length - short conversations may not show noticeable delay
- The issue only manifests after ~30 seconds of inactivity in the conversation
- This affects V1 conversations specifically

### PR DESCRIPTION
**Pull request by amanape**
## Summary of PR

- Memoize event filtering in `ChatInterface`
- Fix conversation history cache key to use stable primitives
- Make loading state check store contents, not just loading-state transition
- Unify mobile and desktop layouts to prevent ChatInterface unmount/remount
- Threshold the layout breakpoint detection (only trigger a React re-render when the width crosses the breakpoint and not on every pixel)
- Removed the auto-scroll* feature.
  - *the `useLayoutEffect` that auto-scrolled on every render. This was a big performance problem; it ran after every render, reading and writing DOM properties during resize. 
  - The hook now has zero work on render. No effects, no DOM access. Scroll only happens when the user clicks the button.
  - This wasn’t working on `main` anyways, and I believe is the common practice to do amongst chat UIs nowadays

## Change Type

- [x] Bug fix
- [ ] New feature
- [ ] Breaking change
- [x] Refactor
- [ ] Other (dependency update, docs, typo fixes, etc.)

## Checklist

- [x] I have read and reviewed the code and I understand what the code is doing.
- [x] I have tested the code to the best of my ability and ensured it works as expected.

## Fixes

Resolves #12704, #12764

## Release Notes

- [x] Include this change in the Release Notes.

---

To run this PR locally, use the following command:

GUI with Docker:
```
docker run -it --rm   -p 3000:3000   -v /var/run/docker.sock:/var/run/docker.sock   --add-host host.docker.internal:host-gateway   -e SANDBOX_RUNTIME_CONTAINER_IMAGE=docker.openhands.dev/openhands/runtime:092280a-nikolaik   --name openhands-app-092280a   docker.openhands.dev/openhands/openhands:092280a
```

### CODE REVIEW

File: frontend/src/components/features/conversation/conversation-main/conversation-main.tsx [hunk 1]
```diff
@@ -1,15 +1,113 @@
-import { useWindowSize } from "@uidotdev/usehooks";
-import { MobileLayout } from "./mobile-layout";
-import { DesktopLayout } from "./desktop-layout";
```
Comment (hieptl) [inline frontend/src/components/features/conversation/conversation-main/conversation-main.tsx:3]: **suggestion:** The desktop-layout.tsx and mobile-layout.tsx files should be removed, as they are no longer used in the codebase. Thank you! 🙏

**Review by hieptl — APPROVED** [review]
Thank you! 🙏
