### PR TITLE
fix: display conversation title in delete confirmation modal

### LINKED ISSUE #11809: [GUI] Show the Conversation Title on the Confirmation Modal Before Deleting
**What problem or use case are you trying to solve?**

**Describe the UX or technical implementation you have in mind**

In the Delete Conversation dialog, there is no clear indication of which conversation is being deleted. The background is barely visible, and no other contextual information is provided. This can create uncertainty and increase the risk of accidentally deleting the wrong conversation.

To address this, we recommend displaying the title of the conversation within the confirmation modal. This would allow users to confidently verify the conversation they are about to delete.

Please refer to the image below for additional context.

Image

**Additional context**

### PR DESCRIPTION
**Pull request by nehaaprasad**
## Summary of PR

Displays the conversation title in the delete confirmation modal so users can verify which conversation they're deleting.

## Change Type

- [x] New feature

## Checklist

- [ ] I have read and reviewed the code and I understand what the code is doing.
- [ ] I have tested the code to the best of my ability and ensured it works as expected.

## Fixes

Resolves #11809

### CODE REVIEW

**Comment by mamoodi** [comment]
amanape will be available next week. I'll get him to take a look. Thank you!

**Comment by hieptl** [comment]
Hi @naaa760, according to the image below, we can display the conversation title directly within the confirmation message instead of presenting it on a separate line.

issue1

For example, the confirmation message could be structured as follows.

> Are you sure you want to delete the "Hello - Initial Greeting" conversation? This action cannot be undone.

File: frontend/src/components/features/conversation-panel/conversation-panel.tsx [hunk 1]
```diff
@@ -214,6 +214,13 @@ export function ConversationPanel({ onClose }: ConversationPanelProps) {
             setConfirmDeleteModalVisible(false);
           }}
           onCancel={() => setConfirmDeleteModalVisible(false)}
+          conversationTitle={
+            selectedConversationId
+              ? conversations.find(
+                  (c) => c.conversation_id === selectedConversationId,
+                )?.title
+              : undefined
+          }
```
Comment (hieptl) [inline frontend/src/components/features/conversation-panel/conversation-panel.tsx]: **suggestion:** Instead of traversing the list of conversations to locate the selected conversation’s title, we can follow the steps below:

**Step 1:** Define a new state variable named selectedConversationTitle:

```ts
const [selectedConversationTitle, setSelectedConversationTitle] =
    React.useState<string | null>(null);
```

**Step 2:** Pass `project.title` when invoking `handleDeleteProject`:

```ts
handleDeleteProject(project.conversation_id, project.title)
``` 

**Step 3:** Update the `handleDeleteProject` function as follows:

```ts
const handleDeleteProject = (conversationId: string, title: string) => {
  setConfirmDeleteModalVisible(true);
  setSelectedConversationId(conversationId);
  setSelectedConversationTitle(title);
};
```

**Step 4:** Pass `selectedConversationTitle` to the `<ConfirmDeleteModal />` component:

```ts
<ConfirmDeleteModal
  onConfirm={() => {
    handleConfirmDelete();
    setConfirmDeleteModalVisible(false);
  }}
  onCancel={() => setConfirmDeleteModalVisible(false)}
  conversationTitle={selectedConversationTitle ?? undefined}
/>
```

**Comment by nehaaprasad** [comment]
@hieptl 
please check it now!

File: frontend/src/components/features/conversation-panel/confirm-delete-modal.tsx [hunk 2]
```diff
@@ -11,22 +11,26 @@ import { I18nKey } from "#/i18n/declaration";
...
 
 export function ConfirmDeleteModal({
   onConfirm,
   onCancel,
+  conversationTitle,
 }: ConfirmDeleteModalProps) {
   const { t } = useTranslation();
 
+  const confirmationMessage = conversationTitle
+    ? `Are you sure you want to delete the "${conversationTitle}" conversation? This action cannot be undone.`
```
Comment (hieptl) [inline frontend/src/components/features/conversation-panel/confirm-delete-modal.tsx]: Hello @naaa760,

Could you please add support for multiple languages to this text? You may refer to the translation.json and declaration.ts files for additional details.

Thank you! 🙏

**Comment by hieptl** [comment]
Hello @naaa760,

Could you please let me know if you are currently working on this pull request?

Thank you! 🙏

**Review by hieptl — APPROVED** [review]
Thank you! 🙏
