### PR TITLE
Fix browser tab not showing the most recent screenshot

### LINKED ISSUE #8387: [Bug]: Browser tab stopped showing the most recent screenshot
**Describe the bug and reproduction steps**  
Our browser tab stop showing screenshot correctly for past actions. Did we change anything related to it recently?  

**Potential solutions**  
<N/A>  

**Logs, Errors, Screenshots, and Additional Context**  
image  

**Issue Created By**: Xingyao Wang on Slack  
**Link to Slack Thread**: https://openhands-ai.slack.com/archives/C086ARSNMGA/p1746799579460279?thread_ts=1746799579.460279&cid=C086ARSNMGA

### PR DESCRIPTION
**Pull request by xingyaoww**
- [ ] This change is worth documenting at https://docs.all-hands.dev/
- [x] Include this change in the Release Notes. If checked, you **must** provide an **end-user friendly** description for your change below

**End-user friendly description of the problem this fixes or functionality this introduces.**

Fixes an issue where the browser tab was not showing the most recent screenshot after browser actions. This ensures that users always see the latest browser state when interacting with web pages.

---
**Summarize what the PR does, explaining any non-trivial design decisions.**

This PR addresses the issue where the browser tab was not showing the most recent screenshot after browser actions.

## Problem
The browser state was not being updated when browser observations were received through the `addAssistantObservation` action.

## Solution
Updated the `observations.ts` file to ensure the browser state (screenshot and URL) is updated in both the `browse` and `browse_interactive` case handlers.

## Changes
- Modified `frontend/src/services/observations.ts` to update browser state in both case handlers
- Added `frontend/__tests__/services/observations.test.tsx` to test the browser state update functionality

After fix - screenshot displays properly

image

---
**Link of any specific issues this addresses:**

Fixes #8387

@xingyaoww can click here to [continue refining the PR](https://app.all-hands.dev/conversations/2d4f2fcd24554e68be9aed63ad700a6d)

---

To run this PR locally, use the following command:
```
docker run -it --rm   -p 3000:3000   -v /var/run/docker.sock:/var/run/docker.sock   --add-host host.docker.internal:host-gateway   -e SANDBOX_RUNTIME_CONTAINER_IMAGE=docker.all-hands.dev/all-hands-ai/runtime:3d848b9-nikolaik   --name openhands-app-3d848b9   docker.all-hands.dev/all-hands-ai/openhands:3d848b9
```

### CODE REVIEW

**Comment by xingyaoww** [comment]
@OpenHands pls fix the npm run test error in CI

File: frontend/src/services/observations.ts [hunk 1]
```diff
@@ -158,6 +158,14 @@ export function handleObservationMessage(message: ObservationMessage) {
         );
         break;
       case "browse":
+        // Make sure to update the browser state with the latest screenshot and URL
```
Comment (xingyaoww) [inline frontend/src/services/observations.ts:161]:
```suggestion
```

File: frontend/src/services/observations.ts [hunk 2]
```diff
@@ -198,6 +206,14 @@ export function handleObservationMessage(message: ObservationMessage) {
         );
         break;
       case "browse_interactive":
+        // Make sure to update the browser state with the latest screenshot and URL
```
Comment (xingyaoww) [inline frontend/src/services/observations.ts:209]:
```suggestion
```

**Review by rbren — APPROVED** [review]
