### PR TITLE
Fix incomplete localization issue #9282

### LINKED ISSUE #9282: [Bug]: Incomplete localization
### Is there an existing issue for the same bug? (If one exists, thumbs up or comment on the issue instead).

- [x] I have checked the existing issues.

### Describe the bug and reproduction steps

Our localization is incomplete again.

- Maximum budget per conversation in USD
- Suggested tasks
- No tasks available
- Specify an amount in USD to add

Are all not appropriately localized.

1. These should have been caught by our localization check. Find out why they were not caught, and *in the most generalizable way possible* fix the check to make sure that these are caught. You must NOT add specific exclusions for these strings, as then the checks will not be able to catch future issues.
2. Run the checks and find all unlocalized strings.
3. Fix them.

### OpenHands Installation

Docker command in README

### OpenHands Version

_No response_

### Operating System

None

### Logs, Errors, Screenshots, and Additional Context

_No response_

### PR DESCRIPTION
**Pull request by neubig**
## Summary

This PR fixes issue #9282 about incomplete localization by addressing multiple critical bugs in the localization check script and localizing all previously unlocalized strings in the frontend.

### 🔧 **Localization Check Script Fixes**
- **Fixed placeholder/alt/aria-label detection**: Removed `"alt"`, `"placeholder"`, and `"aria-label"` from `NON_TEXT_ATTRIBUTES` exclusion list so the script properly detects user-facing text in these attributes
- **Fixed overly broad suggestion file exclusion**: Changed from excluding all files containing "suggestions" to only excluding specific content files (`utils/suggestions/` and `mocks/task-suggestions-handlers.ts`)
- **CRITICAL BUG FIX**: Fixed CSS units regex pattern that was incorrectly filtering out user-facing strings like "Suggested Tasks"
  - **Before**: `/(px|rem|em|vh|vw|vmin|vmax|ch|ex|fr|deg|rad|turn|grad|ms|s)$/`
  - **After**: `/\b\d+(px|rem|em|vh|vw|vmin|vmax|ch|ex|fr|deg|rad|turn|grad|ms|s)$|^(px|rem|em|vh|vw|vmin|vmax|ch|ex|fr|deg|rad|turn|grad|ms|s)$/`
  - Now requires either digits before units or standalone unit strings

### 🌐 **Translation System Updates**
- **Added 25+ new translation keys** with full multi-language support to `translation.json`
- **Regenerated i18n declaration file** with new translation keys
- **Fixed duplicate translation keys** that were causing test failures

### 🔄 **Component Localization**
Updated **15 components** to use proper translation keys instead of hardcoded strings:

| Component | Hardcoded String | Translation Key |
|-----------|------------------|-----------------|
| `repo-provider-links.tsx` | "Add GitHub repos" | `I18nKey.HOME$ADD_GITHUB_REPOS` |
| `branch-dropdown.tsx` | "Select a branch" | `I18nKey.REPOSITORY$SELECT_BRANCH` |
| `repository-dropdown.tsx` | "Select a repo" | `I18nKey.REPOSITORY$SELECT_REPO` |
| `task-suggestions.tsx` | "Suggested Tasks" | `I18nKey.TASKS$SUGGESTED_TASKS` |
| `task-suggestions.tsx` | "No tasks available" | `I18nKey.TASKS$NO_TASKS_AVAILABLE` |
| `payment-form.tsx` | "Specify an amount in USD to add - min $10" | `I18nKey.PAYMENT$SPECIFY_AMOUNT_USD` |
| Token help anchors | aria-label attributes | Proper translation keys |
| `secret-form.tsx` | "Secret already exists" | `I18nKey.SECRETS$SECRET_ALREADY_EXISTS` |
| `custom-model-input.tsx` | aria-label | `I18nKey.MODEL$CUSTOM_MODEL` |
| `invariant.tsx` | placeholder & aria-label | Translation keys |
| `app-settings.tsx` | placeholder | `I18nKey.SETTINGS$MAXIMUM_BUDGET_USD` |
| `git-settings.tsx` | "Disconnect Tokens" | `I18nKey.GIT$DISCONNECT_TOKENS` |
| `llm-settings.tsx` | API key placeholders | Translation keys |
| `secrets-settings.tsx` | "Connect a Git provider to manage secrets" | `I18nKey.SECRETS$CONNECT_GIT_PROVIDER` |

### 🧪 **Testing**
- **Added comprehensive test suite** (`frontend/src/test/localization-fix.test.ts`) to verify the fix
- **Updated failing tests** to expect translation keys instead of translated text
- **All localization checks now pass** with no unlocalized strings found

## Verification

✅ **Localization check script**: `node scripts/check-unlocalized-strings.cjs` - No unlocalized strings found  
✅ **Frontend tests**: All tests pass  
✅ **Frontend build**: Builds successfully  
✅ **Linting**: All code properly formatted  

## Fixes

Closes #9282

## Type of Change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] Improvement (non-breaking change which improves existing functionality)

## Testing

- [x] I have added tests that prove my fix is effective
- [x] I have verified that the localization check script now properly detects unlocalized strings
- [x] I have verified that all previously unlocalized strings are now properly localized
- [x] All existing tests continue to pass

@neubig can click here to [continue refining the PR](https://app.all-hands.dev/conversations/3246560478254750bf968615e9056d5e)

---

To run this PR locally, use the following command:
```
docker run -it --rm   -p 3000:3000   -v /var/run/docker.sock:/var/run/docker.sock   --add-host host.docker.internal:host-gateway   -e SANDBOX_RUNTIME_CONTAINER_IMAGE=docker.all-hands.dev/all-hands-ai/runtime:d825922-nikolaik   --name openhands-app-d825922   docker.all-hands.dev/all-hands-ai/openhands:d825922
```

### CODE REVIEW

**Comment by neubig** [comment]
LGTM, needs another check.

File: frontend/scripts/check-unlocalized-strings.cjs [hunk 1]
```diff
@@ -540,11 +539,15 @@ function isInTranslationContext(path) {
...
 
 function scanFileForUnlocalizedStrings(filePath) {
-  // Skip all suggestion files as they contain special strings
-  if (filePath.includes("suggestions")) {
+  // Skip suggestion content files as they contain special strings that are already properly localized
+  if (filePath.includes("utils/suggestions/") || filePath.includes("mocks/task-suggestions-handlers.ts")) {
     return [];
   }
 
+  if (filePath.includes("task-suggestions.tsx")) {
```
Comment (raymyers) [inline frontend/scripts/check-unlocalized-strings.cjs]: This if is empty.

File: frontend/scripts/check-unlocalized-strings.cjs [hunk 2]
```diff
@@ -540,11 +539,15 @@ function isInTranslationContext(path) {
...
+
+  }
+
```
Comment (neubig) [inline frontend/scripts/check-unlocalized-strings.cjs]:
```suggestion
```
